// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ionzsgnynwnoidykxiyd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlvbnpzZ255bndub2lkeWt4aXlkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5MTEzNzQsImV4cCI6MjA2OTQ4NzM3NH0.BtlDU50duxVAe_I6RPAuXMsHUM65UMSA0VkP_Dr4u5k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});